### ISSUE TITLE
getFieldError usage

### ISSUE THREAD

**Issue by mgcrea** [react-component/field-form#29]
I'm trying to setup validation error state/messages and I can't find how to do it:

- Looks like the `<Field />` component does not pass any validation related prop to its children, (only value/onChange).

- Using `form.getFieldError` in the parent does not work as it's not properly called upon validation.

- Haven't found a `getFieldProps` API to extract validation statuses from the form instance.

Here is a quick code-sandbox: https://codesandbox.io/s/rc-field-form-5jcfm-5jcfm

I know this is alpha software, but it would be great to add some recipe.md file with common use case! Thanks for the great work.

**Comment by zombieJ** [comment]
Hi @mgcrea , here is the sample of it: https://rc-field-form.react-component.now.sh/?selectedKind=rc-field-form&selectedStory=validate&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fsource%2Fpanel

In most case, `getFieldError` is not need since currently we provides `onFinishFailed` function and you can get the errors. And also if you are using condition render it may need to get the error in Field render props.
