### ISSUE TITLE
No way to provide extra keys for validator template messages

### ISSUE THREAD

**Issue by rohit-gohri** [react-component/field-form#68]
I can currently specify my own ValidatorMessages, but no way to provide extra keys for the message template string.

There is a option(`additionalKv`) but it is not being used.
https://github.com/react-component/field-form/blob/c465860a487c85658eafe3eee6cd51ee7443c0ff/src/utils/validateUtil.ts#L43-L58

**Comment by Rfrixy** [comment]
Need this too.

**Comment by devuxer** [comment]
Rules message should be human readable and should not contain kabob-case names like "last-name" or "favorite-color".

However, `name` is used to generate the `id` for the input, and per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), `id` cannot have a space.

So, the template for generating rules should not use `name`. We should be able to specify what it uses to refer to the field. If you have to pick a default, `label` would make a lot more sense (since it's supposed to be human friendly).

**Comment by rohit-gohri** [comment]
@zombieJ  I think this was closed in https://github.com/react-component/field-form/pull/80?

**Comment by zombieJ** [comment]
Yes. This can be closed.
